# Site settings
title: goto epicfailure;
name: Haakon Sporsheim
email: haakon.sporsheim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome site and blog where I reflect upon hardware, software and
  the state of the universe.
  Do not interpret content here as the opinon of my employer.
  Views and opinions are my own.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ieei.github.io" # the base hostname & protocol for your site
twitter_username: haaspors
github_username:  ieei
disqus_shortname: ieeigh

nav-pages:
  - blog
  - resume

# Build settings
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: css
  style: expanded

exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true
